# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
        AppBundle\Entity\Client: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        en_base_de_donnees:
            entity:
                class: AppBundle:Client
                property: login
#        in_memory:
#            memory: 
#                users:
#                    tom:
#                            password: tom
#                            roles: 'ROLE_USER'
#                    admin:
#                            password: admin
#                            roles: 'ROLE_ADMIN'
                

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            provider: en_base_de_donnees
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^adminSecu, roles: ROLE_ADMIN }
        - { path: ^userSecu, roles: [ROLE_USER, ROLE_ADMIN] }